### ISSUE TITLE
running with -e flag and text to encrypt

### ISSUE THREAD

**Issue by accasey** [tslater2006/Pivet#15]
When you run `pivet.exe -e mypassword` to encrypt `mypassword` the program behaves a little unexpectedly.

Instead of encrypting `mypassword` it runs the build process. This is because you need to run `pivet.exe -e` by itself and then type in the password when prompted.

**Comment by accasey** [comment]
It might be nice if when run with the `-e` flag and there is more than one command line argument that it prints a statement saying incorrect usage (or something like that).

**Comment by tslater2006** [comment]
the thinking of not accepting -e password is that you wouldn't want that password in your bash history I'd think. so running -e puts you into a mode where you can type the password without it being visible.

I can adjust the behavior such that if -e is present -> encrypt mode. no matter the number of arguements.

**Comment by tslater2006** [comment]
currently the check is "if 1 parameter, and it is -e"

**Comment by accasey** [comment]
Your proposal sounds fine..
I know the check as I was double-checking how it works v's my notes :)
